global using MyRecipeBook.Comunication.Requests;
global using MyRecipeBook.Comunication.Responses;
global using FluentValidation;
global using MyRecipeBook.Application.Services.Cryptography;
global using MyRecipeBook.Domain.Repositories.User;
global using MyRecipeBook.Exception.ExceptionBase;
global using AutoMapper;
global using MyRecipeBook.Application.Services.AutoMapper;
global using MyRecipeBook.Core;